### ISSUE TITLE
Error in 200-openshift-gitops : "bin_dir" is required, but was not set 

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/terraform-gitops-cluster-config#8]
Getting the below error since yesterday, when executing terraform apply on 200-openshift-gitops layer.

```
│ Error: Missing required argument
│ 
│ The argument "bin_dir" is required, but was not set.
```

terraform init & terraform apply :
[bin_dir_error.txt](https://github.com/cloud-native-toolkit/terraform-gitops-cluster-config/files/9477321/bin_dir_error.txt)

**Comment by triceam** [comment]
This was an artifact created by the introduction to the gitops provider.  Regenerate the latest bill of materials, and it should go away.

**Comment by nheidloff** [comment]
Hi @triceam I have the same issue. I ran iascable build again but still have the issue.

Do I have to throw away my complete Terraform state (output dir) and set up everything again?

**Comment by nheidloff** [comment]
The error disappeared after I re-created everything.
